 manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: necromnomicon
      url-base: https://github.com/necromnomicon     # <--- and this
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3                              # <--- v0.3 only
      import: app/west.yml
    - name: zmk-dongle-screen                     # <--- and these
      remote: necromnomicon # <---
      revision: main                              # <---
  self:
    path: config   
